// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yszhslsluycamhnfwzgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzemhzbHNsdXljYW1obmZ3emd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4NTgxNTcsImV4cCI6MjA1MzQzNDE1N30.bhbvZjMzEosbIJJHjvHoYyu9ga31Y1NsDujLO57M-Kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);